-- Xbyak backs the mid-function hook thunks; it must be enabled before the
-- commonlib include so the Trampoline gains its CodeGenerator overloads.
set_config("commonlib_xbyak", true)

-- CommonLibF4 lives in lib/commonlibf4 as a git submodule.  Clone with
--   git clone --recurse-submodules …
-- or run `git submodule update --init --recursive` in an existing checkout.
-- Set the COMMONLIBF4_PATH environment variable to build against a checkout
-- kept elsewhere instead.
local commonlibf4 = os.getenv("COMMONLIBF4_PATH") or path.join(os.projectdir(), "lib/commonlibf4")
if not os.isdir(commonlibf4) then
    print("CommonLibF4 not found at '" .. commonlibf4 .. "'")
    print("Run: git submodule update --init --recursive")
end
includes(commonlibf4)

set_project("CustomVoicedDialogue")
set_version("0.1.0")
set_license("GPL-3.0")
set_languages("c++23")
set_warnings("allextra")
set_encodings("utf-8")

add_rules("mode.debug", "mode.releasedbg")
add_rules("plugin.vsxmake.autoupdate")

add_defines("COMMONLIB_RUNTIMECOUNT=3", "_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING")

target("CustomVoicedDialogue")
    add_rules("commonlibf4.plugin", {
        name = "CustomVoicedDialogue",
        author = "TheShinyHaxorus",
        description = "Voices unvoiced Fallout 4 dialogue lines with TTS audio generated by the CustomVoicedDialogue companion app.",
        plugin_template = path.join(os.projectdir(), "res/commonlibf4-plugin.cpp.in"),
    })

    add_files("src/**.cpp")
    add_headerfiles("src/**.h")
    add_includedirs("src")
    add_defines("_UNICODE")
    set_pcxxheader("src/PCH.h")
    -- WinHTTP is the localhost client used to talk to the companion server.
    add_syslinks("winhttp")

after_build(function (target)
    -- Workspace staging rule: every compiled plugin stages DLL + PDB + INI under
    -- <project root>/Compile/F4SE/Plugins so Compile/ is a drop-in Data tree.
    local plugins = path.join(os.projectdir(), "..", "Compile", "F4SE", "Plugins")
    os.mkdir(plugins)
    os.cp(target:targetfile(), plugins)
    os.cp(target:symbolfile(), plugins)
    os.cp(path.join(os.projectdir(), "config", "CustomVoicedDialogue.ini"), plugins)
end)
