#pragma once

namespace CustomVoicedDialogue::SilenceFallback
{
	// Picks Data\Sound\Voice\CustomVoicedDialogue\Silence_<N>.wav where N is
	// seconds of silence estimated from the response text's word count, so
	// the subtitle stays readable while the TTS audio is still being
	// generated.  N is clamped to [MinimumSilenceSeconds, 10]; the ten
	// silence files ship with the mod (generated by tools/SilenceGen).
	[[nodiscard]] std::string Pick(std::string_view a_responseText);

	// Same, but sized from a known audio duration instead of text (used as
	// the timing carrier when a session-fresh wav is played directly).
	[[nodiscard]] std::string PickForSeconds(float a_seconds);

	// Exposed for offline unit testing of the estimator.
	[[nodiscard]] std::uint32_t EstimateSeconds(
		std::string_view a_responseText,
		std::uint32_t a_wordsPerSecond,
		std::uint32_t a_minimumSeconds,
		std::uint32_t a_wideCharactersPerWord) noexcept;
}
